---

- import_tasks: postgresql.yml
  when: not patroni_postgresql_exists

- import_tasks: watchdog.yml
  when: patroni_watchdog_mode in ('automatic', 'required')

- name: Install patroni
  ansible.builtin.package:
    name: "{{ patroni_pkgs[ansible_os_family] }}"
    update_cache: yes

- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
  when: patroni_install_haproxy
