---
- block:
    - name: ansible.builtin.deb822_repository requirements
      ansible.builtin.apt:
        name: python3-debian

    - name: Configure postgresql repository
      ansible.builtin.deb822_repository:
        name: postgresql
        types: deb
        uris: "{{ postgresql_apt.uris }}"
        suites: "{{ ansible_distribution_release }}-pgdg"
        components: main
        signed_by: "{{ postgresql_apt.signed_by }}"
      register: repo

    - name: Apt update
      ansible.builtin.apt:
        update_cache: yes
      when: repo.changed

    - name: Ensure postgresql database-cluster manager package
      package:
        name: postgresql-common
        update_cache: yes

    - name: Disable initializing of a default postgresql cluster
      replace:
        path: /etc/postgresql-common/createcluster.conf
        replace: create_main_cluster = false
        regexp: ^#?create_main_cluster.*$
  when: ansible_os_family == "Debian"

- name: Configure postgresql repository
  package:
    name: "{{ postgresql_yum_repo_url }}"
    disable_gpg_check: true
  when: ansible_os_family == "RedHat"

- name: Install postgresql packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - "{{ patroni_postgresql_packages }}"
