---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [patroni, patroni-install, patroni-configure]

- name: Define patroni_postgresql_packages.
  set_fact:
    patroni_postgresql_packages: "{{ __patroni_postgresql_packages | list }}"
  when: patroni_postgresql_packages is not defined

- name: Append haproxy to system packages if needed
  set_fact:
    patroni_system_packages: "{{ __patroni_haproxy_packages | list }}"
  when: patroni_install_haproxy

- name: Define patroni_postgresql_data_dir.
  set_fact:
    patroni_postgresql_data_dir: "{{ __patroni_postgresql_data_dir }}"
  when: patroni_postgresql_data_dir is not defined

- name: Define patroni_postgresql_config_dir.
  set_fact:
    patroni_postgresql_config_dir: "{{ __patroni_postgresql_config_dir }}"
  when: patroni_postgresql_config_dir is not defined

- name: Define patroni_postgresql_bin_dir.
  set_fact:
    patroni_postgresql_bin_dir: "{{ __patroni_postgresql_bin_dir }}"
  when: patroni_postgresql_bin_dir is not defined

- name: Define patroni_postgresql_pgpass.
  set_fact:
    patroni_postgresql_pgpass: "{{ __patroni_postgresql_pgpass }}"
  when: patroni_postgresql_pgpass is not defined
